@IsTest
public with sharing class DiagnosticController_Test {
    
    /*@IsTest
    static void checkDataTest(){
        String result = DiagnosticController.checkData();
        system.assert(result.contains('Validation started'));
    }
    
    @IsTest
    static void populateDataTest(){
        String result = DiagnosticController.populateData();
        
        String result1 = DiagnosticController.checkData();
    }
    
    @IsTest
    static void setUpBatchTest(){
       
    }
    
    @IsTest
    static void runCountTimeBatchTest(){
        String result = DiagnosticController.runCountTimeBatch();
        //system.assert(result.contains('Service Appointments batch update'));
    }
*/
}