public with sharing class Constants { //TODO: Rename to DiagnosticConstants
    public static final String WARNING_STATUS = 'WARNING';
    public static final String FAILED_STATUS = 'FAILED';
    public static final String OK_STATUS = 'OK';
    public static final String DUPLICATED_STATUS = 'DUPLICATED';

    public static final String TEST_ACTION_TYPE = 'Test';
    public static final String EXECUTE_ACTION_TYPE = 'Execute';
}
