public with sharing class Constants { //TODO: Rename to DiagnosticConstants
    public static final String WARNING_STATUS = 'WARNING';
    public static final String FAILED_STATUS = 'FAILED';
    public static final String OK_STATUS = 'OK';
    public static final String DUPLICATED_STATUS = 'DUPLICATED';

    public static final String TEST_ACTION_TYPE = 'Test';
    public static final String EXECUTE_ACTION_TYPE = 'Execute';

    public static final String CUSTOMERS_DATA = 'CUSTOMERS DATA';
    public static final String PRODUCTS_DATA = 'PRODUCTS DATA';
    public static final String OPPORTUNITY_DATA = 'OPPORTUNITY DATA';

    public static final String CRON_EXPRESSION_NAME = 'Job_Cron_Expression';
    public static final String SIZE_JOB_NAME = 'Job_Size';
}
