public inherited sharing class SSACConstants { 
    public static final String WARNING_STATUS = 'WARNING';
    public static final String FAILED_STATUS = 'FAILED';
    public static final String INVALID_STATUS = 'INVALID';
    public static final String UPSERTED_STATUS = 'UPSERTED';
    public static final String OK_STATUS = 'OK';
    public static final String DUPLICATED_STATUS = 'DUPLICATED';
    public static final String CHANGED_STATUS = 'CHANGED';

    public static final String TEST_ACTION_TYPE = 'Test';
    public static final String EXECUTE_ACTION_TYPE = 'Execute';

    public static final String CUSTOMERS_DATA = 'CUSTOMERS DATA';
    public static final String PRODUCTS_DATA = 'PRODUCTS DATA';
    public static final String OPPORTUNITY_DATA = 'OPPORTUNITY DATA';

    public static final String CRON_EXPRESSION_NAME = 'Job_Cron_Expression';
    public static final String SIZE_JOB_NAME = 'Job_Size';
    public static final String REFERENCE_NAME = 'REFERENCE';
    public static final Integer MAX_RECORDS_PER_PAGE = 50;
    


}
