public with sharing class Constants {
    public static final String WARNING_STATUS = 'WARNING';
	public static final String FAILED_STATUS = 'FAILED';
	public static final String OK_STATUS = 'OK';
	public static final String STATUS_DUPLICATE_VALUE = 'DUPLICATED';
    public static final String NAME_API_NAME = 'Name';
    public static final String ACCOUNT_API_NAME = 'Account';
    public static final String CONTACT_API_NAME = 'Contact';
    public static final String ACCOUNT_ID_API_NAME = 'AccountId';
    public static final String LAST_NAME_API_NAME = 'LastName';
    public static final String FIRST_NAME_API_NAME = 'FirstName';
    public static final String EMAIL_API_NAME = 'Email';
    public static final String EMAIL_DOMAIN = '@testmail.com';
    public static List<String> ACCOUNT_NAMES = new List<String> {
        'Social Software',
        'Adept Software',
        'Boss Software',
        'Scope Software',
        'Agile Software',
        'Variable Software',
        'Cornerstone Software',
        'Ascend Software',
        'Consumer Software',
        'Velocity Software',
        'Urge Software',
        'Access Software',
        'Fiber Software',
        'Ideal Software',
        'Marine Software',
        'Intellect Software',
        'Softwaregenics',
        'Point Software',
        'Vision Software',
        'Softserve'
    };

    public static List<String> CONTACTS_FULL_NAME = new List<String> {
        'Mary,Smith',
        'Patricia,Johnson',
        'Jennifer,Williams',
        'Linda,Brown',
        'Elizabeth,Jones',
        'Barbara,Garcia',
        'Susan,Miller',
        'Jessica,Davis',
        'Sarah,Rodriguez',
        'Karen,Martinez',
        'Nancy,Hernandez',
        'Lisa,Lopez',
        'Betty,Gonzalez',
        'Margaret,Wilson',
        'Sandra,Anderson',
        'Ashley,Thomas',
        'Kimberly,Taylor',
        'Emily,Moore',
        'Donna,Jackson',
        'Michelle,Martin',
        'Dorothy,Lee',
        'Carol,Perez',
        'Amanda,Thompson',
        'Melissa,White',
        'Deborah,Harris',
        'Stephanie,Sanchez',
        'Rebecca,Clark',
        'Sharon,Ramirez',
        'Laura,Lewis',
        'Cynthia,Robinson',
        'Kathleen,Walker',
        'Amy,Young',
        'Shirley,Allen',
        'Angela,King',
        'Helen,Wright',
        'Anna,Scott',
        'Brenda,Torres',
        'Pamela,Nguyen',
        'Nicole,Hill',
        'Emma,Flores',
        'Samantha,Green',
        'Katherine,Adams',
        'Christine,Nelson',
        'Debra,Baker',
        'Rachel,Hall',
        'Catherine,Rivera',
        'Carolyn,Campbell',
        'Janet,Mitchell',
        'Ruth,Carter',
        'Maria,Roberts',
        'Katya,Karatnyk',
        'Pavlo,Karatnyk'
    };

    public static List<String> FIRST_NAME = new List<String> {
        
    };

    public static List<String> LAST_NAME = new List<String> {

    };

    public static List<String> EMAIL = new List<String> {

    };
}
